package common

import (
	"io"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xuri/excelize/v2"
)

func Test_htmlToRichText(t *testing.T) {
	type args struct {
		givenFilepath string
		expResult     []excelize.RichTextRun
		expErr        error
	}
	tcs := map[string]args{
		"success": {
			givenFilepath: "testdata/description.html",
			expResult: []excelize.RichTextRun{
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Details",
				},
				{
					Font: nil,
					Text: "\n\n- The H5 Elite features a tempered glass front panel and built-in RGB functionality to showcase various lighting components. With optimized thermal performance and intuitive cable management, the H5 Elite is an ideal chassis for most builds.\n\n- Pre-installed fan on bottom inside panel is angled to cool GPU\n\n- Tempered glass front panel and built-in RGB controller\n\n- Perforated top panel provides optimal ventilation\n\n- Intuitive cable management system with wide channels, hooks, &amp; straps\n\n- Tool-less access to front &amp; side panels\n\n- Front panel supports 2 x 140mm fans or 280mm radiator\n\n- Top panel supports up to 2 x 120mm fans or 240mm radiator\n\n- Includes two pre-installed F140 RGB fans (Case Version) &amp; one F120Q fan (Case Version)\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Tech Specs",
				},
				{
					Font: nil,
					Text: "\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Key Specs",
				},
				{
					Font: nil,
					Text: "\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Motherboard Support:",
				},
				{
					Font: nil,
					Text: " Mini-ITX, Micro-ATX, ATX\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Enclosure Type:",
				},
				{
					Font: nil,
					Text: " Mid-Tower\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Case Material:",
				},
				{
					Font: nil,
					Text: " SGCC Steel, Ultra-clear Tempered Glass, Dark Tinted Tempered Glass (Black only)\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Dimensions",
				},
				{
					Font: nil,
					Text: "\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Height:",
				},
				{
					Font: nil,
					Text: " 464 mm (With Feet)\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Width:",
				},
				{
					Font: nil,
					Text: " 227 mm\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Depth:",
				},
				{
					Font: nil,
					Text: " 446 mm\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Weight:",
				},
				{
					Font: nil,
					Text: " 8.1 kg\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Compatibility &amp; Clearance",
				},
				{
					Font: nil,
					Text: "\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Max CPU Cooler Clearance:",
				},
				{
					Font: nil,
					Text: " Up to 165mm\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Max GPU Clearance:",
				},
				{
					Font: nil,
					Text: " Up to 365mm\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Front Radiator Clearance:",
				},
				{
					Font: nil,
					Text: " 45mm\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Cable Management:",
				},
				{
					Font: nil,
					Text: " Up to 23mm\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Front I/O Ports",
				},
				{
					Font: nil,
					Text: "\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "USB 3.2 Gen 1 Type-A:",
				},
				{
					Font: nil,
					Text: " 1\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "USB 3.2 Gen 2x2 Type-C (20 Gbps):",
				},
				{
					Font: nil,
					Text: " 1\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Headset Audio Jack:",
				},
				{
					Font: nil,
					Text: " 1\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Included Accessories",
				},
				{
					Font: nil,
					Text: "\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Installation screws:",
				},
				{
					Font: nil,
					Text: " 1\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Cable ties:",
				},
				{
					Font: nil,
					Text: " 10\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "RGB Lighting Controller:",
				},
				{
					Font: nil,
					Text: " NZXT RGB Connector: 3 (Support up to 120 LEDs)\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Expansion Slots",
				},
				{
					Font: nil,
					Text: "\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Standard:",
				},
				{
					Font: nil,
					Text: " 7\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Drive Bays",
				},
				{
					Font: nil,
					Text: "\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "2.5&quot;:",
				},
				{
					Font: nil,
					Text: " 1+1\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "3.5&quot;:",
				},
				{
					Font: nil,
					Text: " 1\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Fan Support",
				},
				{
					Font: nil,
					Text: "\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Front:",
				},
				{
					Font: nil,
					Text: " 2 x F Series RGB 140mm (Case Version) included\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Top:",
				},
				{
					Font: nil,
					Text: " 2 x 120mm\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Rear:",
				},
				{
					Font: nil,
					Text: " 1 x 120mm\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Bottom:",
				},
				{
					Font: nil,
					Text: " 1 x F Series Quiet 120mm (Case Version) included\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Filters:",
				},
				{
					Font: nil,
					Text: " All Air Intakes\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Radiator Support",
				},
				{
					Font: nil,
					Text: "\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Front:",
				},
				{
					Font: nil,
					Text: " Up to 280mm\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Top:",
				},
				{
					Font: nil,
					Text: " Up to 240mm\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Rear:",
				},
				{
					Font: nil,
					Text: " Up to 120mm\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Fan Specs",
				},
				{
					Font: nil,
					Text: "\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Model:",
				},
				{
					Font: nil,
					Text: " F140 RGB Fan (Case Version)\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Speed:",
				},
				{
					Font: nil,
					Text: " 500 - 1800 RPM\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Airflow:",
				},
				{
					Font: nil,
					Text: " 24.85 - 89.48 CFM\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Static Pressure:",
				},
				{
					Font: nil,
					Text: " 0.94 - 3.39 mm-H2O\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Noise:",
				},
				{
					Font: nil,
					Text: " 20 - 32.5 dBA\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Fan Connector:",
				},
				{
					Font: nil,
					Text: " 3-pin\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Fan Specs",
				},
				{
					Font: nil,
					Text: "\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Model:",
				},
				{
					Font: nil,
					Text: " F120Q Airflow Fan (Case Version)\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Speed:",
				},
				{
					Font: nil,
					Text: " 1200 ± 240 RPM\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Airflow:",
				},
				{
					Font: nil,
					Text: " 62.18 CFM\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Static Pressure:",
				},
				{
					Font: nil,
					Text: " 1.05 mm-H2O\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Noise:",
				},
				{
					Font: nil,
					Text: " 25.1 dBA\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Fan Connector:",
				},
				{
					Font: nil,
					Text: " 3-pin\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "General",
				},
				{
					Font: nil,
					Text: "\n\n",
				},
				{
					Font: &excelize.Font{
						Bold:         true,
						Italic:       false,
						Underline:    "",
						Family:       "",
						Size:         0,
						Strike:       false,
						Color:        "",
						ColorIndexed: 0,
						ColorTheme:   nil,
						ColorTint:    0,
						VertAlign:    "",
					},
					Text: "Warranty:",
				},
				{
					Font: nil,
					Text: " 2 Years\n",
				},
			},
		},
	}

	for scenario, tc := range tcs {
		tc := tc
		t.Run(scenario, func(t *testing.T) {
			t.Parallel()

			// Given
			f, err := os.Open(tc.givenFilepath)
			require.NoError(t, err)
			defer f.Close()

			htmlText, err := io.ReadAll(f)
			require.NoError(t, err)

			// When
			rs := htmlToRichText(string(htmlText))

			// Then
			require.Equal(t, tc.expResult, rs)
		})
	}
}

func Benchmark_htmlToRichText(b *testing.B) {
	const givenFilepath = "testdata/description.html"

	f, err := os.Open(givenFilepath)
	require.NoError(b, err)
	defer f.Close()

	// Prepare data for benchmark
	htmlText, err := io.ReadAll(f)
	require.NoError(b, err)

	b.Helper()
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_ = htmlToRichText(string(htmlText))
	}
}
